apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: github-eventsource
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`event-source.kube.kabaconde.com`) && PathPrefix(`/push`)
    services:
    - name: webhook-eventsource-svc
      port: 12000
