apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCg0nHQdAm9hy9Q5wug4KNNJvuHJ/rHQc2uA4N+J9YYCcPhJyTZ/UMPifw4LIh2yXiBxYXMC1+fzhj4tUcszcpgy5n9oJt/pheneCxMinAQjlXP33Z3nl4PgtIMXPNlh+yYcpyDAqqTNpVzYnZ76xb7Cmtn6Gr8lgxQkR7NHNTxGKiYT8z4aJD02KDVYshmpYGKA3fHXjfdoMZpLWS6masaOeJ4ZNnTZrqjUnGDVLyUi8ZKdSPNqOlSOaRKLfld6u14I88qfxWbYeyFk3rhmcmSmR5lYToPTYUkti2jbivB4ozZXtKpGaao7wNDKAU/6cwhJm1ENcnKLm60Ms2vMeV7IonnfzuRBsKN5M0UddjMfGQBX3eMXUP3u1aZaGf32POwt8mdar2au4bf2hM94IM1VMbsVZ+o0x8ksleyoH2dcCAGXmU/5cHZDuHqbYNw23t+yRzlwE7QUoN6O0q5y8QEeHl3b8zsrtoM2JTvRQZLDTi6daUX7mS6inFP1gYBnIRHvEDaTy56T3UoSLSCCdh+hOu+hK/kBj86eVLixvrjoW37Ychp39GDJt3nW63Loj5VMqctV/wX/NIob5UOBIxtxucBtaba0AH2STj0TSzEB7teWoCLbGWUaEUFkOVnETBpFuIeqyHOpZdq5Stcj+kN/Pxq2YB9y+VgDmEONWXG0hGQjHRLhv45rHahmTMX5BmqrEifcuFgM+julqW4/qKh8/B8Mi1j+WmM4kcnLk4xIADW3WM5KhAl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque
